### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

### ISSUE THREAD

**Issue by tnavadiya** [callmesusheel/image-background-removal#9]
$python3 seg.py sample.jpg sample.png

Traceback (most recent call last):
  File "seg.py", line 89, in <module>
    MODEL = DeepLabModel(modelType)
  File "seg.py", line 25, in __init__
    graph_def = tf.GraphDef.FromString(open(tarball_path + "/frozen_inference_graph.pb", "rb").read()) 
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

I am getting this error when execute the given command. Can you please help me on this?

**Comment by d-bohn** [comment]
Are you using `tensorflow==2.0.0`? I had this issue when I installed the newest version of `tensorflow`. I resolved the issue by installed `tensorflow==1.14`. I imagine with the recent update to `2.0` there is some broken code. If you (or anyone) has the time to look at the code and update it for the `2.0` release, that would be awesome!

**Comment by tnavadiya** [comment]
Yes Thanks for your response. Its solved using 1.14.
